version: '3.3'

services:
  fermo_gui:
    build:
      context: .
      dockerfile: ./compose/fermo_gui/Dockerfile
    ports:
      - 8001:8001

#    depends_on:
#      - redis
#      - celery_worker
#
#  celery_worker:
#    build:
#      context: .
#      dockerfile: ./compose/fermo_gui/Dockerfile
#    volumes:
#      - .:/fermo_gui
#    command: >
#      hatch run celery -A make_celery worker --loglevel ERROR
#    depends_on:
#      - redis
#
#  redis:
#    image: redis:7-alpine
#    ports:
#      - 6379:6379
#    volumes:
#      - redis:/data
#
#volumes:
#  redis: {}