[project]
name = "fermo"
description = "FERMO dashboard: analysis of liquid chromatography (tandem) mass spectrometry data."
version = "0.8.7"
authors = [
    { name = "Mitja M. Zdouc", email = "mitja.zdouc@wur.nl" }
]
dependencies = [
    "numpy",
    "pandas",
    "matchms",
    "pyteomics",
    "plotly",
    "argparse",
    "dash",
    "dash-cytoscape",
    "dash_bootstrap_components",
    "networkx",
    "ms2query==0.4.3",
    "dash[diskcache]"
]

[project.optional-dependencies]
dev = [
    "pre-commit", 
    "pytest"
]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[tool.setuptools]
packages = ["fermo"]
